apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        annotations:
        # Enable the injector
        vault.hashicorp.com/agent-inject: "true"
        # The role we created in Vault
        vault.hashicorp.com/role: "todo-role"
        # The path to the secret in Vault
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/mongodb"
        # How to format the file inside the pod
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/data/mongodb" -}}
          export MONGO_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      containers:
      - name: backend
        image: pragyanborthakur/devops-server:56
        env:
        - name: MONGO_URL
          value: mongodb+srv://borthakurpragyan15_db_user@database.yzhfipq.mongodb.net/?appName=database
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
