apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# This adds "dev-" to the start of all your resource names automatically
namePrefix: dev-

# This is what Jenkins will update!
images:
  - name: pragyanborthakur/devops-server
    newTag: latest
  - name: pragyanborthakur/devops-client
    newTag: latest

# Add dev-specific labels
commonLabels:
  env: development
